select FNAME ,LNAME ,AGE ,
CASE 
    WHEN AGE>20 THEN 'old'
	ELSE 'young'
END AS Category
FROM [SQL TUTORIAL].[dbo].[EMP_INFO] WHERE AGE is NOT NULL Order by AGE
--IF TWO CONDITIONS MEET THEN EARLY CONDITION IS CONSIDERED